### ISSUE TITLE
feature/xys-store

### ISSUE THREAD

**Issue by XYIAN** [XYIAN/xyian-nextjs#25]
## E-Commerce Page Feature Addition 
Add a store page to function as a basic e-commerce route to order xyian gear. The overall theme should match the rest of the site and contain quick and simple functions. 

### TASKS 

- [ ] create header component for general welcome and short description (maybe add shipping info etc?)  
- [ ] create shopping item component: image, details/breadcrumb, price/add to cart button(should open an popup/overlay with size option), details button(should open a popup/overlay with extra details, add to cart etc) 
- [ ] popup overlay for item add to cart and item details (should be able to do both depending on prop passed) 
- [ ] create cart component (simple as possible) 
- [ ] confirmation / thank you page - when payments are complete a confirmation/thank you page should be displayed (this page should also NOT be added to SEO and should be in robots.txt) 
- [ ] for all images, should be [a skeleton component](https://primereact.org/skeleton/) (from pr) while loading  
- [ ] create footer - add return policy and FAQ?
